### ISSUE TITLE
The zendesk ticket doesn't show any related redmine issue

### ISSUE THREAD

**Issue by cheoAlejo** [apanzerj/NewZDRedmine#5]
Greetings, I installed this app at my zendesk instance and i can successfully see all my redmine projects, i can create issues from the ticket and they are created correctly at redmine, but back at zendesk the ticket doesnt show the related issue anywhere.

These two screenshots show how it is supossed to be, taken from the zendesk marketplace:
![1](https://cloud.githubusercontent.com/assets/10518807/9128384/4e2d37ec-3c8d-11e5-9a84-5afba0b6208c.png)

![2](https://cloud.githubusercontent.com/assets/10518807/9128386/547c8396-3c8d-11e5-9294-9d2a40426a65.png)

### But at my zendesk instance shows like this:
![3](https://cloud.githubusercontent.com/assets/10518807/9128388/6b75733c-3c8d-11e5-86ca-ec909952e9ff.png)

**Im running a Redmine 2.6 instance**

**Comment by apanzerj** [comment]
I'll take a look tomorrow and follow up with you. I may need some extra
info from you. I'm in PST time zone.

**Comment by cheoAlejo** [comment]
Great, thanks for the answer.

**Comment by apanzerj** [comment]
Quick heads up: the "linked to #19" is not part of the plugin. That's the problem/incident classification native to Zendesk.

**Comment by cheoAlejo** [comment]
Mm, ok.

**Comment by apanzerj** [comment]
Hmm. One thing to also note:

The way the plugin works, you should have a private comment on the ticket that points out the issue was pushed to redmine. The fact that it's not making this comment means something is not working quite right but oddly, that's the least likely part not to work. That's just Zendesk talking to Zendesk. There's no reason for that not to happen.

**Comment by apanzerj** [comment]
I sent you an email on your Zendesk ticket.

**Comment by cheoAlejo** [comment]
Ok, ill look right now.

**Comment by cheoAlejo** [comment]
Give me some minutes while i consult my boss. I work for Delfin Systems.

Mm, you mean that when i created the issue from the ticket, a private comment should have been created ?
When i created the issue from zendesk right from thr ticket, nothing happened, no message of success or alert of any kind, however the issue was successfully created at redmine.

**Comment by apanzerj** [comment]
Yes, when you push the ticket to Redmine it should create a private comment on the ticket. Was the ticket a new ticket by any chance? I'm not sure if I built a safeguard for this but you need to make sure the ticket actually exists before you push it to redmine. In other words, make the first comment, save the ticket, push it to redmine.

**Comment by cheoAlejo** [comment]
Hi, I found the problem. Two redmine plugins override the `show` view that returns the recently created issue. I erased the content of those two files and Voilá ! your app works perfect.

The only problem is that Im not a ruby developer and I dont know how to fix the problem without erasing the content of those files completly or without uninstalling those plugins  :disappointed: .

These are the files:
https://github.com/Undev/redmine_simple/blob/master/app/overrides/issues/show.rb
https://github.com/Undev/redmine_undev_git/blob/master/app/overrides/issues/show.rb

I will write to the author of these two plugins, however, do you any last hint ?

**Comment by apanzerj** [comment]
I'll look in a sec

**Comment by apanzerj** [comment]
Best guess and cursory glance my gut says this one: https://github.com/Undev/redmine_undev_git/blob/master/app/overrides/issues/show.rb is the more likely culprit. Specifically looking at the lines to replace things:

https://github.com/Undev/redmine_undev_git/blob/master/app/overrides/issues/show.rb#L4

**Comment by apanzerj** [comment]
Does erasing the content of only one of those files make a difference?

**Comment by cheoAlejo** [comment]
No, i havent done that. I'm going to try.

**Comment by cheoAlejo** [comment]
Yes, your gut was right. The undev_git plugin is the problem.

**Comment by cheoAlejo** [comment]
Actually that plugin have been giving me a lot of trouble, and they give no answer to the issues.
Thanks for all your help my friend, I'll continue tomorrow trying to solve this.
