### ISSUE TITLE
Are contributions to this project welcome?

### ISSUE THREAD

**Issue by tobias-kuendig** [apanzerj/NewZDRedmine#7]
I would like to fix some bugs and make some optimizations to this project.

@apanzerj are contributions to this project welcome? Can you push updates to the official [Zendesk Apps Marketplace](https://www.zendesk.com/apps/redmine/)?

**Comment by apanzerj** [comment]
Contributions are welcome. I can't push directly to the marketplace but I
can request Zendesk to make the updates.

**Comment by tobias-kuendig** [comment]
Okay, great! Thank you for your feedback. I will create pull requests as necessary.
